server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              # - account_email
          github:
            client-id: ${CLIENT_GITHUB_ID}
            client-secret: ${CLIENT_GITHUB_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            scope:
              - read:user
              - user:email
          google:
            clientId: ${CLIENT_GOOGLE_ID}
            clientSecret: ${CLIENT_GOOGLE_SECRET}
            authorization-grant-type: authorization_code
            redirectUri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - openid
              - profile
              - email
        provider:
          kakao:
            authorization-uri:  https://kauth.kakao.com/oauth/authorize
            token-uri:          https://kauth.kakao.com/oauth/token
            user-info-uri:      https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          github:
            authorization-uri:  https://github.com/login/oauth/authorize
            token-uri:          https://github.com/login/oauth/access_token
            user-info-uri:      https://api.github.com/user
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000  # 1시간
front-end:
  redirect: http://localhost:3000/oauth2/redirect

supabase:
  url: ${STORAGE_URL}
  bucket-name: ${STORAGE_BUCKET_NAME}
  access-key: ${STORAGE_KEY}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}
